#!/bin/bash
# Quick Setup Guide for RentRead Payment System

echo "🚀 RentRead Payment System - Quick Start Guide"
echo "=============================================="
echo ""
echo "✅ System Components Installed:"
echo "  1. Payment Page (payment.html)"
echo "  2. Admin Rental Requests Dashboard (admin-rental-requests.html)"
echo "  3. Database Tables (rental_requests, admin_bkash_config)"
echo "  4. API Endpoints for payment management"
echo ""
echo "📋 DATABASE SETUP"
echo "=================="
echo "Tables created:"
echo "  - rental_requests: Stores payment confirmation requests"
echo "  - admin_bkash_config: Stores admin Bkash settings"
echo ""
echo "To verify tables:"
echo "  node scripts/payments/verify-tables.js"
echo ""
echo "To setup tables manually:"
echo "  node scripts/payments/setup-payment-tables.js"
echo ""
echo "🎯 ACCESSING THE SYSTEM"
echo "======================="
echo ""
echo "1. USER RENTAL FLOW:"
echo "   - Home Page: http://localhost:5000"
echo "   - Select book and click 'Rent & Confirm'"
echo "   - Choose days and confirm"
echo "   - Payment page will load automatically"
echo "   - Scan Bkash QR code"
echo "   - Enter transaction ID and confirm"
echo ""
echo "2. ADMIN PAYMENT MANAGEMENT:"
echo "   - URL: http://localhost:5000/admin-rental-requests.html"
echo "   - View pending payment requests"
echo "   - Approve or reject requests"
echo "   - User's rental automatically activates on approval"
echo ""
echo "📱 BKASH CONFIGURATION"
echo "====================="
echo "Default Admin Phone: 01700000000"
echo "Merchant ID: RENTREAD001"
echo ""
echo "To update admin Bkash number:"
echo "  UPDATE admin_bkash_config SET bkash_phone_number = 'YOUR_NUMBER' WHERE admin_id = 1;"
echo ""
echo "🔗 API ENDPOINTS"
echo "================"
echo ""
echo "Create Payment Request:"
echo "  POST /api/rent/request"
echo ""
echo "Get Pending Requests (Admin):"
echo "  GET /api/rent/requests/pending"
echo ""
echo "Approve Request (Admin):"
echo "  POST /api/rent/requests/:id/approve"
echo ""
echo "Reject Request (Admin):"
echo "  POST /api/rent/requests/:id/reject"
echo ""
echo "Get Admin Bkash Config:"
echo "  GET /api/rent/admin-bkash-config"
echo ""
echo "📚 DOCUMENTATION"
echo "================"
echo "Full documentation: PAYMENT_SYSTEM_GUIDE.md"
echo ""
echo "✨ System is ready to use!"
echo "Start the server with: npm start"
echo ""
